# Generated by Django 4.2.3 on 2023-08-13 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "trainee",
            "0002_certificate_trainer_trainingcenter_remove_trainee_id_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enrollment_date", models.DateField()),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="trainee.course"
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="trainee",
            name="certificates",
        ),
        migrations.DeleteModel(
            name="Certificate",
        ),
        migrations.AddField(
            model_name="enrollment",
            name="trainee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="trainee.trainee"
            ),
        ),
    ]
