# Generated by Django 4.2.3 on 2023-08-13 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainee", "0003_enrollment_remove_trainee_certificates_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainee",
            name="address",
            field=models.TextField(default=0),
        ),
    ]
