# Generated by Django 4.2.3 on 2023-08-13 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trainee", "0004_trainee_address"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trainee",
            name="course",
        ),
    ]
