# Generated by Django 4.2.3 on 2023-08-13 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("trainee", "0005_remove_trainee_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="training_period",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="trainee",
            name="course",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                to="trainee.course",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
