# Generated by Django 4.2.3 on 2023-08-13 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trainee", "0006_enrollment_training_period_trainee_course_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trainee",
            name="course",
        ),
    ]
