# Generated by Django 4.2.3 on 2023-08-13 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("trainee", "0007_remove_trainee_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainee",
            name="course",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="trainee.course",
            ),
        ),
        migrations.AlterField(
            model_name="trainee",
            name="address",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="trainee",
            name="age",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
