# Generated by Django 4.2.3 on 2023-08-13 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainee", "0008_trainee_course_alter_trainee_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainer",
            name="designation",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
