# Generated by Django 4.2.3 on 2023-08-14 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainee", "0009_trainer_designation"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingcenter",
            name="contact_email",
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
